version: '2'
services:
  shipmaster:
    build: .
    image: damoti/shipmaster
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/shipmaster:/var/lib/shipmaster
      - /var/run/docker.sock:/var/run/docker.sock
